name: hashicorp-nomad
version: '1.1.6'
version-script: |
  if [ "$SNAPCRAFT_GRADE" = "stable" ]; then
    echo $SNAPCRAFT_PROJECT_VERSION
  else
    echo $SNAPCRAFT_PROJECT_VERSION-$(git rev-parse --short HEAD)
  fi
summary: Workload Orchestration Made Easy
description: A simple and flexible workload orchestrator to deploy and manage containers and non-containerized applications across on-prem and clouds at scale.

grade: stable
confinement: strict
base: core20

architectures:
  - build-on: [amd64, arm64]
    run-on: [amd64, arm64]

parts:
  nomad:
    plugin: go
    go-channel: latest/stable
    source: https://github.com/hashicorp/nomad.git#v$SNAPCRAFT_PROJECT_VERSION
    source-type: git
    build-packages:
      - gcc

apps:
  nomad:
    command: nomad
    plugs:
      - network
      - docker
