name: consul-homelab
version: '1.10.3'
summary: HomeLab - Service Mesh for any runtime or cloud
description: HomeLab - Consul automates networking for simple and secure application delivery.

grade: stable
confinement: strict
base: core20

architectures:
  - build-on: [amd64, arm64]
    run-on: [amd64, arm64]

parts:
  nomad:
    plugin: go
    go-channel: latest/stable
    source-type: git
    source: https://github.com/hashicorp/consul.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    override-pull: |
      # set -x
      snapcraftctl pull
      printenv
      echo "Running on branch: $GITHUB_REF"
      if ! [ "$GITHUB_REF" = "refs/heads/main" ]; then
        echo "Running on non-default branch, appending the short git rev to the version"
        snapcraftctl set-version "$SNAPCRAFT_PROJECT_VERSION-$(git rev-parse --short HEAD)"
        snapcraftctl set-grade "devel"
      fi
    build-packages:
      - gcc

apps:
  consul-homelab:
    command: bin/consul
    plugs:
      - network
      - network-bind
