name: consul-homelab
version: '1.13.3'
summary: HomeLab Consul - Service Mesh for any runtime or cloud
description: HomeLab Consul - Consul automates networking for simple and secure application delivery.
grade: stable
confinement: strict
base: core22
architectures:
  - build-on: [amd64, arm64]
    build-for: amd64
  - build-on: [amd64, arm64]
    build-for: arm64
parts:
  consul:
    plugin: dump
    source: ./
    source-type: local
    build-packages:
      - unzip
    override-pull: |
      set -x
      craftctl default

      # Import the public key, see: https://www.hashicorp.com/security
      gpg --import hashicorp.asc

      # Download the archive and signature files
      curl -Os https://releases.hashicorp.com/consul/${SNAPCRAFT_PROJECT_VERSION}/consul_${SNAPCRAFT_PROJECT_VERSION}_linux_${CRAFT_TARGET_ARCH}.zip
      curl -Os https://releases.hashicorp.com/consul/${SNAPCRAFT_PROJECT_VERSION}/consul_${SNAPCRAFT_PROJECT_VERSION}_SHA256SUMS
      curl -Os https://releases.hashicorp.com/consul/${SNAPCRAFT_PROJECT_VERSION}/consul_${SNAPCRAFT_PROJECT_VERSION}_SHA256SUMS.sig

      # Verify the signature file is untampered
      gpg --verify consul_${SNAPCRAFT_PROJECT_VERSION}_SHA256SUMS.sig consul_${SNAPCRAFT_PROJECT_VERSION}_SHA256SUMS

      # Verify the SHASUM matches the archive
      shasum --ignore-missing --algorithm 256 --check consul_${SNAPCRAFT_PROJECT_VERSION}_SHA256SUMS

      # unzip packages (GitHub Actions runner use Ubuntu)
      # apt-get install unzip --yes
      unzip consul_${SNAPCRAFT_PROJECT_VERSION}_linux_${CRAFT_TARGET_ARCH}.zip
    prime:
      # files in the prime phase/area are available in the final snap package
      - consul
    override-prime: |
      set -x
      craftctl default
      mv consul bin/consul
      chmod +x bin/consul
  consul-wrapper:
    plugin: dump
    source-type: local
    source: ./bin/
    prime:
      # files in the prime phase/area are available in the final snap package
      - daemon.sh
    override-prime: |
      set -x
      craftctl default
      chmod +x daemon.sh
  build-env:
    plugin: dump
    source-type: local
    source: ./
    override-pull: | # craftctl set version="$(craftctl get version)-$CI_ENV_GIT_COMMIT"
      set -x
      craftctl default

      CI_ENV_FILE=".ci.env"
      if test -f "$CI_ENV_FILE"; then
        set -a; . "$CI_ENV_FILE"; set +a

        echo "Running on branch: $CI_ENV_GITHUB_REF"
        if [ -n "$CI_ENV_GITHUB_REF" ] && [ "$CI_ENV_GITHUB_REF" != "refs/heads/main" ]; then
          echo "Running on non-default branch, appending the short git rev to the version"
          snapcraftctl set-version "$(craftctl get version)-$CI_ENV_GIT_COMMIT"
          craftctl set grade="devel"
        fi
      else
          echo "$CI_ENV_FILE does not exist. Skip setting up properties based on CI environment."
      fi
apps:
  consul-homelab:
    command: bin/consul
    plugs:
      - network
      - network-bind
  daemon:
    # SNAP_DATA is backed up and restored across snap refresh and snap revert operations
    # command: bin/consul agent -config-dir $SNAP_DATA/config/
    # we need to move this to a simple wrapper script, since snapcraft doesn't allow = chars in the command property
    # https://bugs.launchpad.net/snapd/+bug/1820055
    command: daemon.sh
    stop-command: bin/consul leave
    restart-condition: always
    daemon: simple
    # don't start service during the snap installation since it needs some configuration files first
    install-mode: disable
    stop-timeout: 10s
    plugs:
      - network
      - network-bind
