name: nomad
version: '1.1.6'
summary: Workload Orchestration Made Easy
description: A simple and flexible workload orchestrator to deploy and manage containers and non-containerized applications across on-prem and clouds at scale.

grade: stable
confinement: strict
base: core20

architectures:
  - build-on: [amd64, arm64]
    run-on: [amd64, arm64]

parts:
  nomad:
    plugin: go
    go-channel: latest/stable
    source-type: git
    source: https://github.com/hashicorp/nomad.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    build-packages:
      - gcc

apps:
  nomad:
    command: bin/nomad
    plugs:
      - network
      - docker
