name: nomad-homelab
version: '1.3.5'
summary: HomeLab Nomad - Workload Orchestration Made Easy
description: HomeLab Nomad - A simple and flexible workload orchestrator to deploy and manage containers and non-containerized applications across on-prem and clouds at scale.
grade: stable
confinement: strict
base: core22
architectures:
  - build-on: [amd64, arm64]
    build-for: amd64
  - build-on: [amd64, arm64]
    build-for: arm64
parts:
  # nomad:
  #   plugin: go
  #   source-type: git
  #   source: https://github.com/hashicorp/nomad.git
  #   source-tag: v$SNAPCRAFT_PROJECT_VERSION
  #   build-packages:
  #     - gcc
  #     # - golang-go
  #   build-snaps:
  #     - go/latest/stable
  nomad:
    plugin: dump
    source: ./
    override-pull: |
      set -x
      craftctl default

      echo "foo"
      printenv

      # Import the public key, see: https://www.hashicorp.com/security
      gpg --import hashicorp.asc

      # Download the archive and signature files
      curl -Os https://releases.hashicorp.com/nomad/${SNAPCRAFT_PROJECT_VERSION}/nomad_${SNAPCRAFT_PROJECT_VERSION}_linux_amd64.zip
      curl -Os https://releases.hashicorp.com/nomad/${SNAPCRAFT_PROJECT_VERSION}/nomad_${SNAPCRAFT_PROJECT_VERSION}_linux_arm64.zip
      curl -Os https://releases.hashicorp.com/nomad/${SNAPCRAFT_PROJECT_VERSION}/nomad_${SNAPCRAFT_PROJECT_VERSION}_SHA256SUMS
      curl -Os https://releases.hashicorp.com/nomad/${SNAPCRAFT_PROJECT_VERSION}/nomad_${SNAPCRAFT_PROJECT_VERSION}_SHA256SUMS.sig

      # Verify the signature file is untampered
      gpg --verify nomad_${SNAPCRAFT_PROJECT_VERSION}_SHA256SUMS.sig nomad_${SNAPCRAFT_PROJECT_VERSION}_SHA256SUMS

      # Verify the SHASUM matches the archive
      shasum --ignore-missing --algorithm 256 --check nomad_${SNAPCRAFT_PROJECT_VERSION}_SHA256SUMS

      # unzip packages (GitHub Actions runner use Ubuntu)
      apt-get install unzip --yes
      unzip nomad_${SNAPCRAFT_PROJECT_VERSION}_linux_amd64.zip
    prime:
      # files in the prime phase/area are available in the final snap package
      - nomad
    override-prime: |
      set -x
      craftctl default
      mv nomad bin/nomad
      chmod +x bin/nomad
  nomad-wrapper:
    plugin: dump
    source-type: local
    source: ./bin/
    prime:
      # files in the prime phase/area are available in the final snap package
      - daemon.sh
    override-prime: |
      set -x
      craftctl default
      chmod +x daemon.sh
  build-env:
    plugin: dump
    source-type: local
    source: ./
    override-pull: | # craftctl set version="$(craftctl get version)-$CI_ENV_GIT_COMMIT"
      set -x
      craftctl default

      CI_ENV_FILE=".ci.env"
      if test -f "$CI_ENV_FILE"; then
        set -a; . "$CI_ENV_FILE"; set +a

        echo "Running on branch: $CI_ENV_GITHUB_REF"
        if [ -n "$CI_ENV_GITHUB_REF" ] && [ "$CI_ENV_GITHUB_REF" != "refs/heads/main" ]; then
          echo "Running on non-default branch, appending the short git rev to the version"
          snapcraftctl set-version "$(craftctl get version)-$CI_ENV_GIT_COMMIT"
          craftctl set grade="devel"
        fi
      else
          echo "$CI_ENV_FILE does not exist. Skip setting up properties based on CI environment."
      fi
apps:
  nomad-homelab:
    command: bin/nomad
    plugs:
      - network
      - network-bind
      # all plugs below requires manual connect after installation
      - network-observe # required to (read-only) access: /usr/sbin/ip
      - mount-observe # required to (read-only) access: /proc/self/mountinfo
  daemon:
    # SNAP_DATA is backed up and restored across snap refresh and snap revert operations
    # command: bin/consul agent -config-dir $SNAP_DATA/config/
    # we need to move this to a simple wrapper script, since snapcraft doesn't allow = chars in the command property
    # https://bugs.launchpad.net/snapd/+bug/1820055
    command: daemon.sh
    # no need for a "stop-command", the daemon/service is simply stopped via SIGINT
    restart-condition: always
    daemon: simple
    # don't start service during the snap installation since it needs some configuration files first
    install-mode: disable
    stop-timeout: 10s
    plugs:
      - network
      - network-bind
      # all plugs below requires manual connect after installation
      - network-observe # required to (read-only) access: /usr/sbin/ip
      - mount-observe # required to (read-only) access: /proc/self/mountinfo
