name: 'Docker CI'

on:
  # run on pushes to main if docker related files were changed
  push:
    branches:
      - main
    paths:
      - 'docker/**'
      - '.github/workflows/docker.yaml'
  # run on pull requests that target the main branch
  pull_request:
    branches:
      - main
    paths:
      - 'docker/**'
      - '.github/workflows/docker.yaml'
  # run weekly on Monday at 12:00
  schedule:
    - cron: '0 12 * * 1'

concurrency:
  # on main, we want all builds to complete even if commits/merging happens faster to make it easier to discover at which point
  # something broke; else, we cancel "old" builds and run/(re)start the build with the latest changes
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}-{1}', github.workflow, github.sha) || format('ci-{0}-{1}', github.workflow, github.ref) }}

jobs:
  matrix_setup:
    name: 'Setup Build Matrix'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: './docker/'

    permissions:
      contents: read

    env:
      REGISTRY: ghcr.io # GitHub Registry

    steps:
      - name: Git - Checkout
        id: git_checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2

      - name: Build Matrix - Setup
        id: set_matrix
        run: |
          echo "::set-output name=matrix::$(python3 -c 'import os, json; print(json.dumps(os.listdir(".")))')"
          echo "::set-output name=image_name_latest::${{ env.REGISTRY }}/${{ github.repository }}/{0}:latest"
          echo "::set-output name=image_name_git_tag::${{ env.REGISTRY }}/${{ github.repository }}/{0}:$(git rev-parse --short HEAD)"
          echo "::set-output name=docker_registry::${{ env.REGISTRY }}"
          echo "::set-output name=docker_working_dir::./docker"
          echo "::set-output name=docker_image_dir::/tmp"
          echo "::set-output name=docker_image_file::/tmp/image.tar"
          echo "::set-output name=docker_artifact_name::tmp_docker_image_{0}"

    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
      image_name_latest: ${{ steps.set_matrix.outputs.image_name_latest }}
      image_name_git_tag: ${{ steps.set_matrix.outputs.image_name_git_tag }}
      docker_registry: ${{ steps.set_matrix.outputs.docker_registry }}
      docker_working_dir: ${{ steps.set_matrix.outputs.docker_working_dir }}
      docker_image_dir: ${{ steps.set_matrix.outputs.docker_image_dir }}
      docker_image_file: ${{ steps.set_matrix.outputs.docker_image_file }}
      docker_artifact_name: ${{ steps.set_matrix.outputs.docker_artifact_name }}

  code_quality:
    name: 'Code Quality Checks'
    needs: [matrix_setup]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: ${{ fromJson(needs.matrix_setup.outputs.matrix) }}

    defaults:
      run:
        shell: bash

    permissions:
      contents: read
      statuses: write

    steps:
      - name: Git - Checkout
        id: git_checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2

      - name: SuperLinter - Lint Dockerfile
        id: superlinter_scan
        uses: github/super-linter/slim@b8641364ca9a79b3cf07f3c4c59a82709cd39094 # renovate: tag=v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          FILTER_REGEX_INCLUDE: .*${{ needs.matrix_setup.outputs.docker_working_dir }}/${{ matrix.package }}/.*
          VALIDATE_ALL_CODEBASE: ${{ github.event_name != 'pull_request' }}
          VALIDATE_DOCKERFILE: true # dockerfilelint
          VALIDATE_DOCKERFILE_HADOLINT: true # hadolint

  docker_build:
    name: 'Build'
    needs: [matrix_setup]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: ${{ fromJson(needs.matrix_setup.outputs.matrix) }}

    defaults:
      run:
        shell: bash

    permissions:
      contents: read

    steps:
      - name: Git - Checkout
        id: git_checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2

      - name: Docker - Set-Up Environment
        id: docker_setup
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25 # renovate: tag=v1

      - name: Docker - Build Artifact # but don't publish yet
        id: docker_build
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229 # renovate: tag=v2
        with:
          context: ${{ needs.matrix_setup.outputs.docker_working_dir }}/${{ matrix.package }}
          push: false
          tags: ${{ format(needs.matrix_setup.outputs.image_name_latest, matrix.package) }},${{ format(needs.matrix_setup.outputs.image_name_git_tag, matrix.package) }}
          # platforms: ${{ steps.docker_setup.outputs.platforms }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # https://github.com/docker/build-push-action/issues/225#issuecomment-727639184
          # https://github.com/docker/buildx/blob/bcfd4348290ecb67122a882e0ef42aa537a51ae6/docs/reference/buildx_build.md#output
          outputs: type=docker,dest=${{ needs.matrix_setup.outputs.docker_image_file }}

      - name: GitHub - Upload Image Artifact
        id: github_upload
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # renovate: tag=v2
        with:
          name: ${{ format(needs.matrix_setup.outputs.docker_artifact_name, matrix.package) }}
          path: ${{ needs.matrix_setup.outputs.docker_image_file }}
          retention-days: 1

  container_security:
    name: 'Container Security Checks'
    needs: [matrix_setup, docker_build]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: ${{ fromJson(needs.matrix_setup.outputs.matrix) }}

    defaults:
      run:
        shell: bash

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Git - Checkout
        id: git_checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2

      - name: GitHub - Download Image Artifact
        id: github_download
        uses: actions/download-artifact@f023be2c48cc18debc3bacd34cb396e0295e2869 # renovate: tag=v2
        with:
          name: ${{ format(needs.matrix_setup.outputs.docker_artifact_name, matrix.package) }}
          path: ${{ needs.matrix_setup.outputs.docker_image_dir }}

      - name: Docker - Load Image
        id: docker_load
        run: docker image load --input ${{ needs.matrix_setup.outputs.docker_image_file }} && docker images

      - name: Snyk - Check for Docker Image Vulnerabilities
        id: snyk_scan
        uses: snyk/actions/docker@7fad562681122205233d1242c3bb39598c5393da # renovate: tag=0.3.0
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ format(needs.matrix_setup.outputs.image_name_latest, matrix.package) }}
          # only report issues medium or higher (aka no low risk issues)
          args: --file=${{ needs.matrix_setup.outputs.docker_working_dir }}/${{ matrix.package }}/Dockerfile --severity-threshold=medium
          sarif: true

      - name: GitHub - Upload result to Code Scanning
        id: github_upload_sarif
        uses: github/codeql-action/upload-sarif@v1
        # always run, even if the previous step failed due to found vulnerabilities (so it vulnerabilities get reported)
        # only run if the sarif file exists
        # only run on pushes on the default branch
        if: hashFiles('snyk.sarif') != '' && github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        with:
          sarif_file: snyk.sarif

  docker_publish:
    name: 'Publish'
    needs: [matrix_setup, code_quality, docker_build, container_security]
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && !github.event.act

    strategy:
      matrix:
        package: ${{ fromJson(needs.matrix_setup.outputs.matrix) }}

    defaults:
      run:
        shell: bash

    permissions:
      contents: read
      packages: write

    steps:
      - name: GitHub - Download Image Artifact
        id: github_download
        uses: actions/download-artifact@f023be2c48cc18debc3bacd34cb396e0295e2869 # renovate: tag=v2
        with:
          name: ${{ format(needs.matrix_setup.outputs.docker_artifact_name, matrix.package) }}
          path: ${{ needs.matrix_setup.outputs.docker_image_dir }}

      - name: Docker - Load Image
        id: docker_load
        run: docker image load --input ${{ needs.matrix_setup.outputs.docker_image_file }}

      - name: Docker - Log into Registry ${{ needs.matrix_setup.outputs.docker_registry }}
        id: docker_login
        uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7 # renovate: tag=v1
        with:
          registry: ${{ needs.matrix_setup.outputs.docker_registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker - Publish Artifact
        id: docker_publish
        run: |
          docker image push ${{ format(needs.matrix_setup.outputs.image_name_git_tag, matrix.package) }}
          docker image push ${{ format(needs.matrix_setup.outputs.image_name_latest, matrix.package) }}
