name: 'General CI'

on:
  # run on pushes to main if snap related files were changed
  push:
    branches:
      - main
  # run on pull requests that target the main branch
  pull_request:
    branches:
      - main
  # run weekly on Monday at 12:00
  schedule:
    - cron: '0 12 * * 1'

jobs:
  code_quality:
    name: 'Code Quality Checks'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: '.'

    permissions:
      contents: read

    steps:
      - name: Git - Checkout
        id: git_checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
        with:
          # Checkout full git history; required by git-leaks, GitGuardian
          fetch-depth: 0

      # using the 'github' format will automatically add github annotations:
      # https://github.com/ibiqlik/action-yamllint/pull/12
      - name: YamlLint - Scan Files
        id: yamllint_scan
        uses: ibiqlik/action-yamllint@81e214fd484713882ce4237cb7cd264d550856cf # renovate: tag=v3
        with:
          file_or_dir: .
          format: github
          config_file: .yamllint.yml

      # TODO: https://github.com/zricethezav/gitleaks-action/pull/34
      - name: Gitleaks - Scan For Commited Secrets
        id: gitleaks_scan
        uses: zricethezav/gitleaks-action@518e4898c0cd1cc5d9aab6627a2eabd46e81d8da # renovate: tag=v1

      - name: GitGuardian - Scan For Commited Secrets
        uses: GitGuardian/ggshield-action@a5226e0a63850e276df1c71a81129fb82fc6e8cc # renovate: tag=v1.1.0
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
