name: "Repository CI"

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - edited
      - reopened
      # - review_requested
    branches:
      - main

jobs:
  repository:
    # TODO: pin to a sha tag and update automatically:
    # https://github.com/renovatebot/renovate/issues/12212
    uses: busybeaver/homelab-shared/.github/workflows/repository.yaml@main
    secrets:
      REPOSITORY_ASSISTANT_APP_ID: ${{ secrets.REPOSITORY_ASSISTANT_APP_ID }}
      REPOSITORY_ASSISTANT_PRIVATE_KEY: ${{ secrets.REPOSITORY_ASSISTANT_PRIVATE_KEY }}
