name: "Repository CI"

on:
  # run on pushes to main
  push:
    branches:
      - main
      - gh-readonly-queue/main/**
  # run on pull requests that target the main branch
  pull_request:
    branches:
      - main
  # run on pull request events
  pull_request_target:
    types:
      - opened
      - synchronize
      - edited
      - reopened
      # - review_requested
    branches:
      - main

jobs:
  repository:
    uses: busybeaver/homelab-shared/.github/workflows/repository.yaml@df22eb14dfa074e53c0745b62ca862b3a82f70aa # v1.0.82
    secrets:
      REPOSITORY_ASSISTANT_APP_ID: ${{ secrets.REPOSITORY_ASSISTANT_APP_ID }}
      REPOSITORY_ASSISTANT_PRIVATE_KEY: ${{ secrets.REPOSITORY_ASSISTANT_PRIVATE_KEY }}
