name: "Repository CI"

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      # - review_requested
    branches:
      - main

concurrency:
  # on main, we want all builds to complete even if commits/merging happens faster to make it easier to discover at which point
  # something broke; else, we cancel "old" builds and run/(re)start the build with the latest changes
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}-{1}', github.workflow, github.sha) || format('ci-{0}-{1}', github.workflow, github.ref) }}

jobs:
  repository:
    # TODO: pin to a sha tag
    uses: busybeaver/homelab-shared/.github/workflows/repository.yaml@main
    secrets:
      REPOSITORY_ASSISTANT_APP_ID: ${{ secrets.REPOSITORY_ASSISTANT_PRIVATE_KEY }}
      REPOSITORY_ASSISTANT_PRIVATE_KEY: ${{ secrets.REPOSITORY_ASSISTANT_PRIVATE_KEY }}
