name: "Repository CI"

on:
  # run on pushes to main
  push:
    branches:
      - main
      - gh-readonly-queue/main/**
  # run on pull requests that target the main branch
  pull_request:
    branches:
      - main
  # run on pull request events
  pull_request_target:
    types:
      - opened
      - synchronize
      - edited
      - reopened
      # - review_requested
    branches:
      - main

permissions:
  contents: read

jobs:
  repository:
    # timeout-minutes: 20
    uses: busybeaver/homelab-shared/.github/workflows/repository.yaml@471eac81b3c7c08a0f5a0ddd6cd79559a0ae7e61 # v1.1.103
    secrets:
      REPOSITORY_ASSISTANT_APP_ID: ${{ secrets.REPOSITORY_ASSISTANT_APP_ID }}
      REPOSITORY_ASSISTANT_PRIVATE_KEY: ${{ secrets.REPOSITORY_ASSISTANT_PRIVATE_KEY }}
