name: "Repository CI"

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      # - review_requested
    branches:
      - main

jobs:
  repository:
    # TODO: pin to a sha tag and update automatically:
    # https://github.com/renovatebot/renovate/issues/12212
    uses: busybeaver/homelab-shared/.github/workflows/repository.yaml@38d3cec78432c1160d0f9da0d97a91e4190b71f8
    secrets:
      REPOSITORY_ASSISTANT_APP_ID: ${{ secrets.REPOSITORY_ASSISTANT_APP_ID }}
      REPOSITORY_ASSISTANT_PRIVATE_KEY: ${{ secrets.REPOSITORY_ASSISTANT_PRIVATE_KEY }}
