name: 'Snapcraft'

on:
  # run on main to master if snap related files were changed
  push:
    branches:
      - main
    paths:
      - 'snapcraft.yaml'
      - '.github/workflows/**'
  # run on pull requests that target the main branch
  pull_request:
    branches:
      - main
  # run weekly on Monday at 12:00
  schedule:
    - cron: '0 12 * * 1'

jobs:
  snapcraft:
    name: 'Snapcraft'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: '.'

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Snapcraft - Build Artifact
        id: snapcraft_build
        uses: snapcore/action-build@v1

      - name: GitHub - Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: snap
          path: ${{ steps.snapcraft_build.outputs.snap }}
