name: 'Snapcraft CI'

on:
  # run on pushes to main if snap related files were changed
  push:
    branches:
      - main
      - gh-readonly-queue/main/**
  # run on pull requests that target the main branch
  pull_request:
    branches:
      - main
  # run weekly on Monday at 12:00
  schedule:
    - cron: '0 12 * * 1'
  # trigger releases manually
  workflow_dispatch:
    inputs:
      publish_release:
        description: 'Publish release to the Snapcraft store'
        required: true
        type: choice
        default: 'false'
        options:
          - 'true'
          - 'false'

concurrency:
  # on main, we want all builds to complete even if commits/merging happens faster to make it easier to discover at which point
  # something broke; else, we cancel "old" builds and run/(re)start the build with the latest changes
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}-{1}', github.workflow, github.sha) || format('ci-{0}-{1}', github.workflow, github.ref) }}

jobs:
  matrix_setup:
    name: 'Setup Build Matrix'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: './snaps/'

    permissions:
      contents: read

    steps:
      - name: Git - Checkout
        id: git_checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3

      - name: Build Matrix - Setup
        id: set_matrix
        run: |
          echo "::set-output name=matrix::$(python3 -c 'import os, json; print(json.dumps(os.listdir(".")))')"
          echo "::set-output name=snap_working_dir::./snaps"
          echo "::set-output name=snap_dir::/tmp"
          echo "::set-output name=snap_file::/tmp/package.snap"
          echo "::set-output name=snap_artifact_name::tmp_{0}.snap"

    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
      snap_working_dir: ${{ steps.set_matrix.outputs.snap_working_dir }}
      snap_dir: ${{ steps.set_matrix.outputs.snap_dir }}
      snap_file: ${{ steps.set_matrix.outputs.snap_file }}
      snap_artifact_name: ${{ steps.set_matrix.outputs.snap_artifact_name }}

  snapcraft_build:
    name: 'Build'
    needs: [matrix_setup]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: ${{ fromJson(needs.matrix_setup.outputs.matrix) }}

    defaults:
      run:
        shell: bash

    permissions:
      contents: read

    steps:
      - name: Git - Checkout
        id: git_checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3

      - name: Snapcraft - Set up Build Environment
        id: snapcraft_setup
        # prefix all env variables with "CI_ENV_" to ensure these do not clash with env variables within the snapcraft build environment
        # https://gist.github.com/mihow/9c7f559807069a03e302605691f85572
        run: printenv | sed -e '/^#/d;/^\s*$/d' -e "s/'/'\\\''/g" -e "s/=\(.*\)/='\1'/g" | sed -e 's/^/CI_ENV_/' > .ci.env
        working-directory: ${{ needs.matrix_setup.outputs.snap_working_dir }}/${{ matrix.package }}

      - name: Snapcraft - Build Artifact
        id: snapcraft_build
        uses: snapcore/action-build@ea14cdeb353272f75977040488ca191880509a8c # tag=v1
        with:
          path: ${{ needs.matrix_setup.outputs.snap_working_dir }}/${{ matrix.package }}

      - name: GitHub - Move Snap Artifact
        id: move_artifact
        run: |
          mv ${{ steps.snapcraft_build.outputs.snap }} ${{ needs.matrix_setup.outputs.snap_file }}

      - name: GitHub - Upload Snap Artifact
        id: github_upload_snap
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3
        with:
          name: ${{ format(needs.matrix_setup.outputs.snap_artifact_name, matrix.package) }}
          path: ${{ needs.matrix_setup.outputs.snap_file }}
          retention-days: 1

  snapcraft_test:
    name: 'Install and Test'
    needs: [matrix_setup, snapcraft_build]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: ${{ fromJson(needs.matrix_setup.outputs.matrix) }}

    env:
      GOSS_VERSION: v0.3.16

    defaults:
      run:
        shell: bash

    permissions:
      contents: read

    steps:
      - name: Git - Checkout
        id: git_checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3

      - name: GitHub - Download Snap Artifact
        id: github_download
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # tag=v3
        with:
          name: ${{ format(needs.matrix_setup.outputs.snap_artifact_name, matrix.package) }}
          path: ${{ needs.matrix_setup.outputs.snap_dir }}

      - name: GitHub - Get Test Parameter
        id: test_parameter
        run: |
          TEST_WORKING_DIR=${{ needs.matrix_setup.outputs.snap_working_dir }}/${{ matrix.package }}/tests
          echo "::set-output name=test_working_dir::${TEST_WORKING_DIR}"
          echo "::set-output name=test_result_file::goss_test_results.xml"
          echo "::set-output name=snap_logs_name::snap_logs_{0}.log"
          mkdir -p ${TEST_WORKING_DIR}

      - name: Snapcraft - Pre Test Setup
        id: snapcraft_setup
        run: |
          echo "Install snap package:"
          sudo snap install --color=never --dangerous ${{ needs.matrix_setup.outputs.snap_file }}
          SETUP_FILE=./setup.sh
          if test -f "$SETUP_FILE"; then
            echo "$SETUP_FILE exists. Going to run setup:"
            sh ./$SETUP_FILE
          else
            echo "$SETUP_FILE does not exist. Skip setup."
          fi
        working-directory: ${{ steps.test_parameter.outputs.test_working_dir }}
        env:
          SERVICE_NAME: ${{ matrix.package }}

      - name: Goss - Setup
        uses: e1himself/goss-installation-action@88e5a33ec3f7d299fee2e259ff1a6032cb0cdd11 # renovate: tag=v1.0.4
        with:
          version: ${{ env.GOSS_VERSION }}

      - name: GitHub - Check for Test File Existence
        id: check_test_file
        uses: andstor/file-existence-action@f02338908d150e00a4b8bebc2dad18bd9e5229b0 # tag=v1.1.0
        with:
          files: ${{ steps.test_parameter.outputs.test_working_dir }}/goss.yaml

      - name: Goss - Test Artifact
        id: goss_test
        if: steps.check_test_file.outputs.files_exists == 'true'
        run: goss validate --format junit --max-concurrent 1 | tee ${{ steps.test_parameter.outputs.test_result_file }}
        working-directory: ${{ steps.test_parameter.outputs.test_working_dir }}
        env:
          SERVICE_NAME: ${{ matrix.package }}

      - name: Snapcraft - Post Test Teardown
        id: snapcraft_teardown
        if: always()
        run: |
          TEARDOWN_FILE=./teardown.sh
          if test -f "$TEARDOWN_FILE"; then
            echo "$TEARDOWN_FILE exists. Going to run service-specific teardown:"
            sh ./$TEARDOWN_FILE
          else
            echo "$TEARDOWN_FILE does not exist. Skip service-specific teardown."
          fi

          echo "Running general teardown..."
          SNAP_LOGS_FILE="snap_${SERVICE_NAME}.log"
          # according to the shellcheck docs, the check should be disabled in this scenario (see last bullet point):
          # https://github.com/koalaman/shellcheck/wiki/SC2024#rationale
          # shellcheck disable=SC2024
          sudo snap logs "${SERVICE_NAME}" > "$SNAP_LOGS_FILE"
          echo "::set-output name=snap_logs::$(pwd)/${SNAP_LOGS_FILE}"
          echo "Snap logs found at \"$SNAP_LOGS_FILE\":"
          cat "$SNAP_LOGS_FILE"
        working-directory: ${{ steps.test_parameter.outputs.test_working_dir }}
        env:
          SERVICE_NAME: ${{ matrix.package }}

      - name: GitHub - Upload Snap Logs
        id: github_upload_logs
        if: always()
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3
        with:
          name: ${{ format(steps.test_parameter.outputs.snap_logs_name, matrix.package) }}
          path: ${{ steps.snapcraft_teardown.outputs.snap_logs }}
          retention-days: 7

      - name: GitHub - Generate App Token
        id: github_generate_app_token
        uses: tibdex/github-app-token@f717b5ecd4534d3c4df4ce9b5c1c2214f0f7cd06 # tag=v1.6.0
        if: always() && steps.check_test_file.outputs.files_exists == 'true'
        with:
          # https://github.com/EnricoMi/publish-unit-test-result-action/issues/161
          app_id: ${{ secrets.UNIT_TEST_RESULTS_REPORTER_APP_ID }}
          private_key: ${{ secrets.UNIT_TEST_RESULTS_REPORTER_PRIVATE_KEY }}

      - name: GitHub - Publish Unit Test Results
        id: github_publish_results
        uses: EnricoMi/publish-unit-test-result-action@b9f6c61d965bcaa18acc02d6daf706373a448f02 # tag=v1.40
        if: always() && steps.check_test_file.outputs.files_exists == 'true'
        with:
          github_token: ${{ steps.github_generate_app_token.outputs.token }}
          check_name: Test Results (Snap - ${{ matrix.package }})
          files: ${{ steps.test_parameter.outputs.test_working_dir }}/${{ steps.test_parameter.outputs.test_result_file }}
          # we only add github checks to the PR/commit, but don't create PR comments; reason is that comments will not
          # be replaced but always newly added due to (it looks for "github-actions" user instead of the github app user):
          # https://github.com/EnricoMi/publish-unit-test-result-action/blob/ae7c14a87cf1a1200805b487debc65963bdb3f2d/python/publish/publisher.py#L493
          comment_mode: off

  snapcraft_publish:
    name: 'Publish'
    needs: [matrix_setup, snapcraft_test, snapcraft_build]
    runs-on: ubuntu-latest

    if: github.event_name == 'workflow_dispatch' && github.event.inputs.publish_release == 'true' && !github.event.act

    strategy:
      matrix:
        package: ${{ fromJson(needs.matrix_setup.outputs.matrix) }}

    defaults:
      run:
        shell: bash

    permissions:
      contents: read

    steps:
      - name: GitHub - Download Snap Artifact
        id: github_download
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # tag=v3
        with:
          name: ${{ format(needs.matrix_setup.outputs.snap_artifact_name, matrix.package) }}
          path: ${{ needs.matrix_setup.outputs.snap_dir }}

      - name: Snapcraft - Publish Artifact
        id: snapcraft_publish
        uses: snapcore/action-publish@0a8d537ae06f4a292e8b4ef1084cd5631b3c6871 # tag=v1
        with:
          # Generate via snapcraft (available on ubuntu or via 'brew' on macOS):
          # snapcraft export-login --snaps="nomad-homelab,consul-homelab" --acls="package_access,package_push,package_update,package_release" exported.txt
          store_login: ${{ secrets.SNAPCRAFT_STORE_LOGIN }}
          snap: ${{ needs.matrix_setup.outputs.snap_file }}
          # https://github.community/t/do-expressions-support-ternary-operators-to-change-their-returned-value/18114/3
          # The condition evaluates to a boolean, which is implicitly cast to a number and used as array index, where false = 0 and true = 1.
          release: ${{ fromJSON('["edge", "stable"]')[github.ref == format('refs/heads/{0}', github.event.repository.default_branch)] }}
