name: 'Snapcraft CI'

on:
  # run on main to master if snap related files were changed
  push:
    branches:
      - main
    paths:
      - 'snaps/**'
      - '.github/workflows/**'
  # run on pull requests that target the main branch
  pull_request:
    branches:
      - main
    paths:
      - 'snaps/**'
      - '.github/workflows/**'
  # run weekly on Monday at 12:00
  schedule:
    - cron: '0 12 * * 1'

jobs:
  matrix_setup:
    name: 'Setup Build Matrix'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: './snaps/'

    permissions:
      contents: read

    steps:
      - name: Git - Checkout
        id: git_checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2

      - name: Build Matrix - Setup
        id: set_matrix
        run: echo "::set-output name=matrix::$(python2 -c 'import os, json; print json.dumps(os.listdir("."))')"

    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}

  snapcraft:
    name: 'Build, Test, and Publish'
    needs: matrix_setup
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: ${{ fromJson(needs.matrix_setup.outputs.matrix) }}

    env:
      PUBLISH_ARTIFACT: false
      SNAP_WORKING_DIR: './snaps'

    defaults:
      run:
        shell: bash

    permissions:
      contents: read

    steps:
      - name: Git - Checkout
        id: git_checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2

      - name: Snapcraft - Build Artifact
        id: snapcraft_build
        uses: snapcore/action-build@a400bf1c2d0f23074aaacf08a144813c3c20b35d # renovate: tag=v1
        with:
          path: '${{ env.SNAP_WORKING_DIR }}/${{ matrix.package }}'

      - name: Snapcraft - Install and Test Artifact
        id: snapcraft_test
        run: |
          sudo snap install --color=never --dangerous ${{ steps.snapcraft_build.outputs.snap }}
          echo '-----------------'
          TEST_FILE=${{ env.SNAP_WORKING_DIR }}/${{ matrix.package }}/tests.sh
          if test -f "$TEST_FILE"; then
            echo "$TEST_FILE exists. Running tests:"
            sh ./$TEST_FILE
          else
              echo "$TEST_FILE does not exist. Skipping tests."
          fi

      - name: GitHub - Upload Artifact
        id: github_upload
        uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074 # renovate: tag=v2
        with:
          name: ${{ matrix.package }}.snap
          path: ${{ steps.snapcraft_build.outputs.snap }}

      - name: Snapcraft - Publish Artifact
        id: snapcraft_publish
        uses: snapcore/action-publish@f1879414dc5500e02a36f3d715bca6ddd438c913 # renovate: tag=v1
        if: github.event_name == 'push' && github.ref == github.event.repository.default_branch && env.PUBLISH_ARTIFACT == 'true'
        with:
          # Generate via (snapcraft is available on ubuntu or via 'brew' on macOS:
          # snapcraft export-login --snaps="nomad-homelab,consul-homelab" --acls="package_access,package_push,package_update,package_release" exported.txt
          store_login: ${{ secrets.SNAPCRAFT_STORE_LOGIN }}
          snap: ${{ steps.snapcraft_build.outputs.snap }}
          release: '${{ github.ref == github.event.repository.default_branch ? "stable" : "edge" }}'
